name = "flyology_object_storage_sqlite"
description = "SQLite catalog backend for Flyology Object Storage"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-object-storage"
tags = ["ada", "aws", "object-storage", "s3", "sqlite"]

project-files = ["flyology_object_storage_sqlite.gpr"]

[[depends-on]]
flyology_object_storage = "=0.1.0-dev"

[origin]
commit = "5eaf79cf12358c1402b5b7d7ed0a6ec74df6a628"
subdir = "sqlite"
url = "git+https://github.com/flyology-ada/flyology-object-storage.git"
