name = "flyology_postgres_sql_v15"
description = "Native PostgreSQL 15 parser and owned Ada AST"
version = "0.1.1-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-postgres"
tags = ["ada", "postgres", "sql", "parser", "ast"]

project-files = ["sql_v15.gpr"]

[[depends-on]]
flyology_postgres_sql_core = "~0.1.1-dev"

[origin]
commit = "f9101bc486e76f458d424a2ce93f916a6fc29839"
subdir = "sql/v15"
url = "git+https://github.com/flyology-ada/flyology-postgres.git"
