name = "flyology_postgres_sql_v15"
description = "Native PostgreSQL 15 parser and owned Ada AST"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-postgres"
tags = ["ada", "postgres", "sql", "parser", "ast"]
project-files = ["sql_v15.gpr"]

[[depends-on]]
flyology_postgres_sql_core = "~0.1.0-dev"

[origin]
commit = "f8ad1c48a05f3e777b81a46b2b96ff61474d212e"
subdir = "sql/v15"
url = "git+https://github.com/flyology-ada/flyology-postgres.git"
