name = "gnat_flyology_native"
version = "16.2.0-patchset.1.1.1"
provides = ["gnat=16.2.0"]
description = "GNAT native compiler with a validated gnat-patches aggregate"
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
website = "https://github.com/flyology-ada/gnat-patches"

auto-gpr-with = false

[configuration]
disabled = true

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib64"

[environment."case(os)".macos]
PATH.prepend = "${CRATE_ROOT}/bin"
DYLD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib"

[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.1-gcc-16.2.0/gnat-flyology-native-gcc-16.2.0-patchset-1.1.1-linux-x86_64.tar.gz"
hashes = ["sha256:78d65090bbd1517402e7aca4e7495f1a7f65f5f8efc0ea151928a862f8b3ab26"]

[origin."case(os)".linux."case(host-arch)".aarch64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.1-gcc-16.2.0/gnat-flyology-native-gcc-16.2.0-patchset-1.1.1-linux-aarch64.tar.gz"
hashes = ["sha256:0e0a310525d8ae9341568bfa59e5dd97157354bef03df11bf4a1778ae2176abf"]

[origin."case(os)".macos."case(host-arch)".aarch64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.1-gcc-16.2.0/gnat-flyology-native-gcc-16.2.0-patchset-1.1.1-macos-aarch64.tar.gz"
hashes = ["sha256:e4c9f2a4d220a8780a678a84b7298cfea28cad16b010b6dfd8620913a91718c9"]
