name = "gnat_flyology_native"
version = "15.3.0-patchset.1.1.1"
provides = ["gnat=15.3.0"]
description = "GNAT native compiler with a validated gnat-patches aggregate"
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
website = "https://github.com/flyology-ada/gnat-patches"

auto-gpr-with = false

[configuration]
disabled = true

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib64"

[environment."case(os)".macos]
PATH.prepend = "${CRATE_ROOT}/bin"
DYLD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib"

[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.1-gcc-15.3.0/gnat-flyology-native-gcc-15.3.0-patchset-1.1.1-linux-x86_64.tar.gz"
hashes = ["sha256:745b54519244ac62f488f0ceb7b27b36dfc483e33ba79e4581bb490001cd95c4"]

[origin."case(os)".linux."case(host-arch)".aarch64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.1-gcc-15.3.0/gnat-flyology-native-gcc-15.3.0-patchset-1.1.1-linux-aarch64.tar.gz"
hashes = ["sha256:8ea2f842c25c15e4d446286d561bbd8333a19e1238947ce3c6a062aa73b77310"]

[origin."case(os)".macos."case(host-arch)".aarch64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.1-gcc-15.3.0/gnat-flyology-native-gcc-15.3.0-patchset-1.1.1-macos-aarch64.tar.gz"
hashes = ["sha256:f4b77d9479ed07ba18ce79f75727bfbf37bdf5aec97a2059cdc588aea60c633e"]
