name = "gnat_flyology_native"
version = "13.2.0-patchset.1.1.0"
provides = ["gnat=13.2.0"]
description = "GNAT native compiler with a validated gnat-patches aggregate"
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
website = "https://github.com/flyology-ada/gnat-patches"

auto-gpr-with = false

[configuration]
disabled = true

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib64"

[environment."case(os)".macos]
PATH.prepend = "${CRATE_ROOT}/bin"
DYLD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib"

[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.0-gcc-13/gnat-flyology-native-gcc-13.2.0-patchset-1.1.0-linux-x86_64.tar.gz"
hashes = ["sha256:0a1ab2c7e0275a0cb340cd331aef767a81a04becf8adc8840cb3fbaec56cbec0"]

[origin."case(os)".linux."case(host-arch)".aarch64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.0-gcc-13/gnat-flyology-native-gcc-13.2.0-patchset-1.1.0-linux-aarch64.tar.gz"
hashes = ["sha256:894c39d86eb52f3827fdd1dd9dfe7f30ae7334c3f37c48bdf8676582ddddeec4"]

[origin."case(os)".macos."case(host-arch)".aarch64]
binary = true
url = "https://github.com/flyology-ada/gnat-patches/releases/download/patchset-1.1.0-gcc-13/gnat-flyology-native-gcc-13.2.0-patchset-1.1.0-macos-aarch64.tar.gz"
hashes = ["sha256:b1effa47c7e2327ba87febaf84f920135c32c087ae277a45e5ba71e095c179d1"]
