name = "flyology_bench"
description = "Adaptive nanosecond-scale benchmarking for Ada"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://flyology.org/guide/benchmarking/"
tags = ["ada", "benchmark", "performance", "statistics"]
project-files = ["flyology_bench.gpr"]

[[depends-on]]
gnat = ">=13 & <17"

[[actions]]
type = "test"
command = ["./scripts/test.sh"]

[origin]
commit = "516ccb6399474c5791a99e838b1449659c18ae6b"
subdir = "flyology_bench"
url = "git+https://github.com/flyology-ada/flyology.git"
