name = "flyology_allocators"
description = "Caller-owned memory allocation algorithms for Ada"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://flyology.org/"
tags = ["ada", "allocators", "embedded", "memory", "systems"]
project-files = ["flyology_allocators.gpr"]

[[depends-on]]
gnat = ">=13 & <17"

[build-switches]
"*" = { Compile_Checks = "warnings" }

[[actions]]
type = "test"
command = ["./scripts/test.sh"]

[origin]
commit = "243833e635b2fc4f990d86d32624c4f1b7e9951d"
subdir = "flyology_allocators"
url = "git+https://github.com/flyology-ada/flyology.git"
