name = "flyology_quic"
description = "Ada-native QUIC transport for Flyology tasks"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://http.flyology.org/"
tags = ["ada", "quic", "transport", "udp"]
project-files = ["flyology_quic.gpr"]

[[depends-on]]
flyology = "~0.1.0-dev"

[[actions]]
type = "test"
command = ["./scripts/test.sh"]

[origin]
commit = "019b3cd9b5a69046cb49d6877a4411f2caabac36"
subdir = "flyology_quic"
url = "git+https://github.com/flyology-ada/flyology-http.git"
