name = "flyology_iri"
description = "Allocation-conscious URI, IRI, and URL reference parser"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://http.flyology.org/guide/iri/"
tags = ["ada", "uri", "iri", "url", "parser"]
project-files = ["flyology_iri.gpr"]

[[actions]]
type = "test"
command = ["./scripts/test.sh"]

[origin]
commit = "cf5ec9d615d8c094a60d58e087a0fc994a13fac7"
subdir = "flyology_iri"
url = "git+https://github.com/flyology-ada/flyology-http.git"
